// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import { BASE, SITE, SITE_TITLE, SITE_DESCRIPTION, GITHUB_URL } from './src/consts';

// The deployment path is written down once, in src/consts.ts (docs/DECISIONS.md D5).
// Nothing here - and nothing in src/ - may hardcode it.
export default defineConfig({
  site: SITE,
  base: BASE,
  trailingSlash: 'ignore',

  // The toolbar renders into every page and would appear in spike captures and
  // reviewer screenshots, so it is off everywhere rather than off by habit.
  devToolbar: { enabled: false },

  integrations: [
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,

      // The site owns its 404 (phase 7); Starlight's would claim the route first.
      disable404Route: true,

      social: [{ icon: 'github', label: 'GitHub', href: GITHUB_URL }],

      // Phase 7 restyles Starlight onto the site's tokens rather than theming it.
      // The stylesheet is a placeholder hook until then.
      customCss: ['./src/styles/starlight.css'],

      // No explicit sidebar while the collection is one page: an autogenerated
      // group over a single entry renders an empty rail and a mobile menu button
      // that opens onto nothing. Starlight's default listing is honest at this
      // size. Phase 4 lands the ~24 pages and phase 7 replaces this with the six
      // named groups in docs/SITEMAP.md.
    }),
  ],
});
