// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import { satteri } from '@astrojs/markdown-satteri';

import { baseLinks } from './src/plugins/base-links.mjs';

import { BASE, SITE, SITE_TITLE, SITE_DESCRIPTION, GITHUB_URL } from './src/consts';

// The deployment path is written down once, in src/consts.ts (docs/DECISIONS.md D5).
// Nothing here - and nothing in src/ - may hardcode it.
export default defineConfig({
  site: SITE,
  base: BASE,
  trailingSlash: 'ignore',

  // Markdown links are authored root-absolute and resolved against `base` here.
  // See the plugin for why this cannot be left to authoring discipline.
  markdown: { processor: satteri({ mdastPlugins: [baseLinks] }) },

  // The toolbar renders into every page and would appear in spike captures and
  // reviewer screenshots, so it is off everywhere rather than off by habit.
  devToolbar: { enabled: false },

  integrations: [
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,

      // The site owns its 404 (phase 7); Starlight's would claim the route first.
      disable404Route: true,

      social: [{ icon: 'github', label: 'GitHub', href: GITHUB_URL }],

      // Phase 7 restyles Starlight onto the site's tokens rather than theming it.
      // The stylesheet is a placeholder hook until then.
      customCss: ['./src/styles/starlight.css'],

      // The six groups and their order are locked in docs/SITEMAP.md, and the
      // order is the argument: a reader can stop after any group and have
      // something that works. Items are listed rather than autogenerated so the
      // order is the one the IA specifies, not alphabetical. Phase 7 gives the
      // labels their monospace uppercase treatment; this is routing, not styling.
      sidebar: [
        {
          label: 'Getting started',
          items: [
            { slug: 'docs' },
            { slug: 'docs/what-it-does' },
            { slug: 'docs/quickstart' },
            { slug: 'docs/requirements' },
          ],
        },
        {
          label: 'Core concepts',
          items: [
            { slug: 'docs/concepts/scope-and-key' },
            { slug: 'docs/concepts/record-lifecycle' },
            { slug: 'docs/concepts/leases-and-waiting' },
            { slug: 'docs/concepts/outcomes' },
            { slug: 'docs/concepts/payloads-and-codecs' },
            { slug: 'docs/concepts/fingerprints' },
          ],
        },
        {
          label: 'Using it',
          items: [
            { slug: 'docs/annotated-methods' },
            { slug: 'docs/http-endpoints' },
            { slug: 'docs/the-engine' },
            { slug: 'docs/joining-your-transaction' },
            { slug: 'docs/lifecycle-callbacks' },
          ],
        },
        {
          label: 'Storage',
          items: [
            { slug: 'docs/storage/choosing' },
            { slug: 'docs/storage/jdbc' },
            { slug: 'docs/storage/redis' },
            { slug: 'docs/storage/in-memory' },
            { slug: 'docs/storage/writing-a-store' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'docs/reference/configuration' },
            { slug: 'docs/reference/annotation' },
            { slug: 'docs/reference/http' },
            { slug: 'docs/reference/javadoc' },
          ],
        },
        {
          label: 'Operating it',
          items: [
            { slug: 'docs/operating/purging-and-retention' },
            { slug: 'docs/operating/security' },
            { slug: 'docs/operating/limitations' },
            { slug: 'docs/operating/upgrading' },
          ],
        },
      ],
    }),
  ],
});
